1. Handle Error using the error property of the observable

```typescript
@Component({
  selector: 'app-available-places',
  standalone: true,
  templateUrl: './available-places.component.html',
  styleUrl: './available-places.component.css',
  imports: [PlacesComponent, PlacesContainerComponent]
})
export class AvailablePlacesComponent implements OnInit {
  places = signal<Place[] | undefined>(undefined);

  isFetching =signal(false)
  isError=signal('')
  private httpClient= inject(HttpClient)
  private destoyRef= inject(DestroyRef)
  ngOnInit(): void {
    this.isFetching.set(true)
    const getRequestSubscription=this.httpClient.get<{places:Place[]}>('http://localhost:3000/places')
    .pipe(
      map((val)=>val.places)
    ).subscribe(
      {
        next: (places) => {
        // Handle the response data here
        this.places.set(places)
      },
      error: (err) => {
         // Handle any errors that occur
        this.isError.set("Something went wrong")
        this.isFetching.set(false)
       
        console.error('Error occurred:', err);
      },
      complete: () => {
        // Handle completion of the observable stream
        console.log('Request completed.');
        this.isFetching.set(false)
      }
      });

    this.destoyRef.onDestroy(()=>{
      getRequestSubscription.unsubscribe()
    })
  }
}

```
